---
# file: roles/mysql/tasks/debconf.yml

- name: debconf for mysql-server-5.5
  debconf:
    name=mysql-server-5.5
    question={{ item.question }}
    value={{ item.value }}
    vtype={{ item.vtype }}
  with_items:
    - {question: 'mysql-server-5.5/root_password', value: '{{ mysql_root_password }}', vtype: password}
    - {question: 'mysql-server-5.5/root_password_again', value: '{{ mysql_root_password }}', vtype: password}
    - {question: 'mysql-server-5.5/start_on_boot', value: true, vtype: boolean }
  