---
# file: roles/mysql/tasks/users.yml

- name: mysql user for powerdns
  mysql_user:
    name={{ pdns_gmysql_user }}
    password={{ pdns_gmysql_password }}
    priv='*.*:ALL'
    state=present
    login_user={{ mysql_root }}
    login_password={{ mysql_root_password }}
    