---
# file: roles/mysql/tasks/packages.yml

- name: be sure mysql-server is installed
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - mysql-server-5.5
    - python-mysqldb
    # - libmysqlclient-dev
