---
# file: roles/cleanup/tasks/designate.yml

- name: 'check designate process'
  shell:
    ps -ef | grep 'bin/designate-' | grep -v grep -q; echo $?
  register: result

- name: '[clenaup] pkill designate'
  shell:
    pkill designate
  when: result.stdout == '0'

- name: '[cleanup] designate'
  file:
    path={{ item }}
    state=absent
  with_items:
    - /srv/designate/
  