---
# package version
keystone_version: 2013.1.2-5.1

# debconf
auth_token: password
admin_password: password
admin_user: admin
admin_project_name: admin
region_name: regionOne
admin_email: admin@example.org
admin_role_name: admin

# keystone.conf
bind_host: 0.0.0.0
debug: True
verbose: True
policy_file: policy.json
policy_default_rule: admin_required
member_role_name: _member_
sql_connection: sqlite:////var/lib/keystone/keystone.sqlite
identity_driver: keystone.identity.backends.ldap.Identity
catalog_driver: keystone.catalog.backends.sql.Catalog
token_driver: keystone.token.backends.sql.Token
policy_driver: keystone.policy.backends.sql.Policy
ec2_driver: keystone.contrib.ec2.backends.kvs.Ec2
token_format: uuid
# ldap
ldap_url: ldap://localhost
ldap_user: cn=admin,dc=example,dc=org
ldap_suffix: dc=example,dc=org
ldap_use_dumb_member: True
ldap_allow_subtree_delete: False
ldap_dumb_member: cn=dumb,dc=nonexistent
ldap_query_scope: sub
# users
user_tree_dn: dc=example,dc=org
user_id_attribute: uid
user_name_attribute: uid
user_mail_attribute: mail
user_allow_create: False
user_allow_update: False
user_allow_delete: False
# projects
tenant_tree_dn: ou=Projects,dc=auth,dc=example,dc=org
tenant_desc_attribute: description
tenant_allow_create: True
tenant_allow_update: True
tenant_allow_delete: True
# roles
role_tree_dn: ou=Roles,dc=auth,dc=example,dc=org
role_allow_create: True
role_allow_update: True
role_allow_delete: True
# groups
group_tree_dn: ou=Groups,dc=auth,dc=example,dc=org
group_desc_attribute: description
group_allow_create: True
group_allow_update: True
group_allow_delete: True
# domains
domain_tree_dn: ou=Domains,dc=auth,dc=example,dc=org
domain_allow_create: True
domain_allow_update: True
domain_allow_delete: True
