---
# file: roles/pdns/tasks/debconf.yml

- name: '[pdns] debconf pdns-backend-mysql/password-confirm'
  debconf:
    name=pdns-backend-mysql
    question='pdns-backend-mysql/password-confirm'
    value='{{ gmysql_password }}'
    vtype=password
