---
# file: roles/pdns/task/pdns-server.yml

- name: '[pdns] packages are installed'
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - pdns-server
    - pdns-backend-mysql

- name: '[pdns] configuration is prepared'
  template:
    src=pdns.conf.j2
    dest=/etc/powerdns/pdns.conf
  notify:
    - restart pdns

- name: '[pdns] mysql configuration is prepared'
  template:
    src=pdns.local.gmysql.conf.j2
    dest=/etc/powerdns/pdns.d/pdns.local.gmysql.conf
  notify:
    - restart pdns
