---
# file: roles/pdns/task/pdns-server.yml

- name: '[pdns] packages are installed'
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - pdns-server
    - pdns-backend-mysql

- name: '[pdns] configuration is prepared'
  template:
    src=pdns.conf.j2
    dest=/etc/powerdns/pdns.conf
  notify:
    - restart pdns

- name: '[pdns] mysql configuration is prepared'
  template:
    src=pdns.local.gmysql.conf.j2
    dest=/etc/powerdns/pdns.d/pdns.local.gmysql.conf
  notify:
    - restart pdns

- name: check DDL
  shell:
    echo 'show tables' | mysql -u {{ gmysql_user }} --password={{ gmysql_password }} {{ gmysql_dbname }}
  register: result

- name: 'execute DDL to MySQL'
  shell:
    mysql -u {{ gmysql_user }} --password={{ gmysql_password }} {{ gmysql_dbname }} < /usr/share/dbconfig-common/data/pdns-backend-mysql/install/mysql
  when: result.stdout == ''
  