---
# file: roles/pdns/tasks/pdns.yml

- name: backend configuration
  template:
    src=pdns.local.gmysql.conf.j2
    dest=/etc/powerdns/pdns.d/pdns.local.gmysql.conf
  notify:
    - restart pdns

- name: check DDL
  shell:
    echo 'show tables' | mysql -u {{ pdns_gmysql_user }} --password={{ pdns_gmysql_password }} {{ pdns_gmysql_dbname }}
  register: result

- name: execute DDL
  shell:
    mysql -u {{ pdns_gmysql_user }} --password={{ pdns_gmysql_password }} {{ pdns_gmysql_dbname }} < /usr/share/dbconfig-common/data/pdns-backend-mysql/install/mysql
  when: result.stdout == ''
  