---
- hosts: designate
  sudo: yes
  roles:
    - {role: cleanup, tags: ['cleanup']}
    - {role: common, tags: ['development', 'mysql', 'pdns', 'rabbitmq', 'designate']}
    - {role: mysql, tags: ['development', 'mysql']}
    - {role: pdns, tags: ['development','pdns']}
    - {role: rabbitmq, tags: ['development', 'rabbitmq']}
    - {role: designate, tags: ['development', 'designate']}
