---
# roles/ssh/tasks/main.yml
- name: be sure configured sshd
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  tags:
    - sshd
  notify:
    - restart sshd
    