---
# file: roles/mysql/tasks/databases.yml

- name: create a new database
  mysql_db:
    name={{ item }}
    state=present
    encoding=utf8
    login_user={{ mysql_root }}
    login_password={{ mysql_root_password }}
  with_items:
    - "{{ mysql_dbname }}"
