---
# file: roles/designate/tasks/designate.yml

- name: '[designate] packages'
  apt:
    pkg='{{ item }}'
    state=present
  with_items:
    - python-virtualenv

- name: '[designate] python packages'
  pip:
    requirements='/srv/designate/designate/{{ item }}'
    virtualenv=/srv/designate/.venv
    virtualenv_site_packages=yes
  sudo_user: '{{ designate_user }}'
  with_items:
    - requirements.txt
    - test-requirements.txt

- name: '[designate] install'
  shell: '../.venv/bin/python setup.py develop'
  args:
    chdir: /srv/designate/designate
  sudo_user: '{{ designate_user }}'

- name: '[designate] directories'
  file:
    path='{{ item }}'
    owner=designate
    group=designate
    mode=0700
    state=directory
    recurse=yes
  with_items:
    - /srv/designate/lib/designate
    - /srv/designate/log/designate

- name: '[designate] designate.conf'
  template:
    src=designate.conf.j2
    dest=/srv/designate/designate/etc/designate/designate.conf
    owner=designate
    group=designate
    mode=0600

- name: '[designate] sync database'
  shell:
    /srv/designate/.venv/bin/designate-manage --config-dir /srv/designate/designate/etc/designate/ database sync
  sudo_user: '{{ designate_user }}'

- name: '[designate] checking central service'
  shell:
    ps -ef | grep designate-central | grep -v grep -q; echo $?
  register: result_central

- name: '[designate] central service started'
  shell:
    nohup /srv/designate/.venv/bin/designate-central --config-dir /srv/designate/designate/etc/designate/ &
  sudo_user: '{{ designate_user }}'
  when: result_central.stdout != '0'

- name: '[designate] checking API service'
  shell:
    ps -ef | grep designate-api | grep -v grep -q; echo $?
  register: result_api

- name: '[designate] API service started'
  shell:
    nohup /srv/designate/.venv/bin/designate-api --config-dir /srv/designate/designate/etc/designate/ &
  sudo_user: '{{ designate_user }}'
  when: result_api.stdout != '0'

- name: '[designate] Pool Manager service initialize'
  shell:
    /srv/designate/.venv/bin/designate-manage --config-dir /srv/designate/designate/etc/designate/ pool-manager-cache sync
  sudo_user: '{{ designate_user }}'
 
- name: '[designate] checking Pool Manager service'
  shell:
    ps -ef | grep designate-pool-manager | grep -v grep -q; echo $?
  register: result_pool
 
- name: '[designate] Pool Manager service started'
  shell:
    nohup /srv/designate/.venv/bin/designate-pool-manager --config-dir /srv/designate/designate/etc/designate/ &
  sudo_user: '{{ designate_user }}'
  when: result_pool.stdout != '0'

- name: '[designate] checking mdns service'
  shell:
    ps -ef | grep designate-mdns | grep -v grep -q; echo $?
  register: result_mdns

- name: '[designate] mdns service started'
  shell:
    nohup /srv/designate/.venv/bin/designate-mdns --config-dir /srv/designate/designate/etc/designate/ &
  sudo_user: '{{ designate_user }}'
  when: result_mdns.stdout != '0'
