---
- name: prepare slapd setup
  copy: src={{ item }} dest=/tmp/
  with_items:
    - change_core_schema.ldif
    - add_dc_ou_for_keystone.ldif
    - add_users.ldif
    - add_module_memberof.ldif
    - add_olcOverlay_memberof.ldif
- name: setup cn=config
  command: ldapmodify -Y EXTERNAL -H ldapi:// -f /tmp/change_core_schema.ldif
- include: memberof.yml
- include: organizationalUnit.yml
#- name: ldapadd users
#  command: ldapmodify -x -D {{ rootdn }} -w {{ rootpw }} -H ldap:// -f /tmp/{{ item }}.ldif
#  with_items:
#    - add_users
- name: cleanup temporary files
  command: rm -f /tmp/{{ item }}.ldif
  with_items:
    - change_core_schema
    - add_module_memberof
    - add_olcOverlay_memberof
    - People
    - ServerAdmin
    - ProjectUser
    - Projects
    - Roles
    - Groups
    - Domains
    - organization_dc
#    - add_users.ldif
