---
- name: prepare users ldif
  template: src=add_users.ldif.j2 dest=/tmp/add_users.ldif
  with_items:
    - users:
        - { uid: 'user01', cn: 'yamada_taro', desc: 'net', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20001', gidNumber: '20000', sn: 'yamada' }
        - { uid: 'user02', cn: 'tanaka_jiro', desc: 'net', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20002', gidNumber: '20000', sn: 'tanaka' }
        - { uid: 'user03', cn: 'sato_saburo', desc: 'net', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20003', gidNumber: '20000', sn: 'sato' }
        - { uid: 'user04', cn: 'nakamura_shiro', desc: 'net', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20004', gidNumber: '20000', sn: 'nakamura' }
        - { uid: 'user05', cn: 'suzuki_goro', desc: 'net', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20005', gidNumber: '20000', sn: 'suzuki' }
        - { uid: 'user11', cn: 'yamada_taro', desc: 'com', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20011', gidNumber: '20000', sn: 'yamada' }
        - { uid: 'user12', cn: 'tanaka_jiro', desc: 'com', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20012', gidNumber: '20000', sn: 'tanaka' }
        - { uid: 'user13', cn: 'sato_saburo', desc: 'com', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20013', gidNumber: '20000', sn: 'sato' }
        - { uid: 'user14', cn: 'nakamura_shiro', desc: 'com', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20014', gidNumber: '20000', sn: 'nakamura' }
        - { uid: 'user15', cn: 'suzuki_goro', desc: 'com', password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '20015', gidNumber: '20000', sn: 'suzuki' }
        - { uid: 'service-admin', cn: 'service-admin', dn: $organization_dn, password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '2000', gidNumber: '2000', sn: 'service-admin', homeDirectory: '/noexistence' }
        - { uid: 'keystone', cn: 'keystone', dn: $organization_dn, password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '2001', gidNumber: '2000', sn: 'keystone', homeDirectory: '/var/lib/keystone' }
        - { uid: 'nova', cn: 'nova', dn: $organization_dn, password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '2002', gidNumber: '2000', sn: 'nova', homeDirectory: '/var/lib/nova' }
        - { uid: 'swift', cn: 'swift', dn: $organization_dn, password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '2003', gidNumber: '2000', sn: 'swift', homeDirectory: '/var/lib/swift' }
        - { uid: 'glance', cn: 'glance', dn: $organization_dn, password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '2004', gidNumber: '2000', sn: 'glance', homeDirectory: '/var/lib/glance' }
        - { uid: 'cinder', cn: 'cinder', dn: $organization_dn, password: '{SSHA}qlkQl5tkHOKqTIu0MiwUlhWlf9TfrQce', uidNumber: '2005', gidNumber: '2000', sn: 'cinder', homeDirectory: '/var/lib/cinder' }
- name: check users
  shell: |
    ldapsearch -x -b {{ basedn }} -h localhost uid=user01 | grep -q '^dn:'; echo $?
  register: result
- name: add users
  command: ldapadd -x -h localhost -D {{ rootdn }} -w {{ rootpw }} -f /tmp/add_users.ldif
  when: result.stdout != '0'
